export const SET_STUDENT_NAME = 'SET_STUDENT_NAME';
export const SET_TEST_INFO = 'SET_TEST_INFO';
export const UPDATE_PRETEST_INFO = 'UPDATE_PRETEST_INFO';
export const UPDATE_POSTTEST_INFO = 'UPDATE_POSTTEST_INFO';
export const UPDATE_LECTURE_INFO = 'UPDATE_LECTURE_INFO';

// Braille training action types
export const STORE_BRAILLE_LETTER_RESULTS = 'STORE_BRAILLE_LETTER_RESULTS';
export const STORE_BRAILLE_WORD_RESULTS = 'STORE_BRAILLE_WORD_RESULTS';
export const UPDATE_BRAILLE_TRAINING_PHASE = 'UPDATE_BRAILLE_TRAINING_PHASE';
export const RESET_BRAILLE_TRAINING = 'RESET_BRAILLE_TRAINING';
