export const SET_STUDENT_NAME = 'SET_STUDENT_NAME';
export const SET_TEST_INFO = 'SET_TEST_INFO';
export const UPDATE_PRETEST_INFO = 'UPDATE_PRETEST_INFO';
export const UPDATE_POSTTEST_INFO = 'UPDATE_POSTTEST_INFO';
export const UPDATE_LECTURE_INFO = 'UPDATE_LECTURE_INFO';
